-- Smoke test 用的精简 schema(只保留推荐系统需要的表)
DROP TABLE IF EXISTS recommend_exposure_log;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS user_behavior;
DROP TABLE IF EXISTS dish_tag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS dish;
DROP TABLE IF EXISTS dish_category;
DROP TABLE IF EXISTS canteen_window;
DROP TABLE IF EXISTS canteen;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  student_no VARCHAR(32),
  real_name VARCHAR(64) NOT NULL,
  college VARCHAR(128),
  grade VARCHAR(32),
  taste_preference VARCHAR(255),
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE canteen (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  location VARCHAR(255) NOT NULL,
  open_time VARCHAR(100),
  description VARCHAR(500),
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE canteen_window (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  canteen_id BIGINT NOT NULL,
  merchant_id BIGINT,
  name VARCHAR(100) NOT NULL,
  floor VARCHAR(32),
  description VARCHAR(500),
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dish_category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  sort INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dish (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  window_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  image VARCHAR(500),
  price DECIMAL(10,2) NOT NULL,
  description VARCHAR(1000),
  taste VARCHAR(100),
  calories INT,
  avg_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  sales_count INT NOT NULL DEFAULT 0,
  view_count INT NOT NULL DEFAULT 0,
  favorite_count INT NOT NULL DEFAULT 0,
  like_count INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  type VARCHAR(32) NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, type)
);

CREATE TABLE dish_tag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dish_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  UNIQUE(dish_id, tag_id)
);

CREATE TABLE user_behavior (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  behavior_type VARCHAR(32) NOT NULL,
  behavior_weight DECIMAL(6,2) NOT NULL DEFAULT 1.00,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorite (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, dish_id)
);

CREATE TABLE comment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  content VARCHAR(1000) NOT NULL,
  rating DECIMAL(3,2) NOT NULL,
  reply VARCHAR(1000),
  status INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PAID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  dish_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

CREATE TABLE recommend_exposure_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  trace_id VARCHAR(64) NOT NULL,
  user_id BIGINT,
  scenario VARCHAR(32) NOT NULL,
  ab_variant VARCHAR(8) NOT NULL DEFAULT 'A',
  dish_id BIGINT NOT NULL,
  rank_position INT NOT NULL,
  score DECIMAL(8,4),
  action VARCHAR(16) NOT NULL,
  request_uri VARCHAR(255),
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
